api/urls.py
from __future__ import absolute_import
from django.urls import re_path
import api.views

urlpatterns = [
    re_path(r'^(?P<kind>catalogs$)', api.views.plist_api),
    re_path(r'^(?P<kind>catalogs)/(?P<filepath>.*$)', api.views.plist_api),
    re_path(r'^(?P<kind>manifests$)', api.views.plist_api),
    re_path(r'^(?P<kind>manifests)/(?P<filepath>.*$)', api.views.plist_api),
    re_path(r'^(?P<kind>pkgsinfo$)', api.views.plist_api),
    re_path(r'^(?P<kind>pkgsinfo)/(?P<filepath>.*$)', api.views.plist_api),
    re_path(r'^(?P<kind>icons$)', api.views.file_api),
    re_path(r'^(?P<kind>icons)/(?P<filepath>.*$)', api.views.file_api),
    re_path(r'^(?P<kind>pkgs$)', api.views.file_api),
    re_path(r'^(?P<kind>pkgs)/(?P<filepath>.*$)', api.views.file_api),
]

pkgsinfo/urls.py
from __future__ import absolute_import
from django.urls import re_path
import pkgsinfo.views

urlpatterns = [
    re_path(r'^$', pkgsinfo.views.index),
    re_path(r'^__get_process_status$', pkgsinfo.views.status),
    re_path(r'^_json$', pkgsinfo.views.getjson),
    re_path(r'^(?P<pkginfo_path>^.*$)', pkgsinfo.views.detail)
]

pkgsinfo/models.py
"""
pkgsinfo/models.py
"""

from __future__ import absolute_import
from django.db import models
import os
import re
import logging
from collections import defaultdict
from multiprocessing.pool import ThreadPool
from xml.parsers.expat import ExpatError

from django.conf import settings
from process.utils import record_status
from catalogs.models import Catalog
from api.models import Plist, MunkiFile, \
                       FileReadError, FileWriteError, FileDeleteError
from munkiwebadmin.wrappers import readPlist, writePlistToString


REPO_DIR = settings.MUNKI_REPO_DIR
CATALOGS_PATH = os.path.join(REPO_DIR, 'catalogs')
PKGSINFO_PATH = os.path.join(REPO_DIR, 'pkgsinfo')
PKGSINFO_PATH_PREFIX_LEN = len(PKGSINFO_PATH) + 1
PKGSINFO_STATUS_TAG = 'pkgsinfo_list_process'

LOGGER = logging.getLogger('munkiwebadmin')


#####################################################
# version comparison classes and utilities
# much of this lifted from and adapted from the Python distutils.version code
# which was deprecated with Python 3.10
#####################################################

def _cmp(x, y):
    """
    Replacement for built-in function cmp that was removed in Python 3

    Compare the two objects x and y and return an integer according to
    the outcome. The return value is negative if x < y, zero if x == y
    and strictly positive if x > y.
    """
    return (x > y) - (x < y)


class MunkiLooseVersion():
    '''Class based on distutils.version.LooseVersion to compare things like
    "10.6" and "10.6.0" as equal'''

    component_re = re.compile(r'(\d+ | [a-z]+ | \.)', re.VERBOSE)

    def parse(self, vstring):
        """parse function from distutils.version.LooseVersion"""
        # I've given up on thinking I can reconstruct the version string
        # from the parsed tuple -- so I just store the string here for
        # use by __str__
        self.vstring = vstring
        components = [x for x in self.component_re.split(vstring) if x and x != '.']
        for i, obj in enumerate(components):
            try:
                components[i] = int(obj)
            except ValueError:
                pass

        self.version = components

    def __str__(self):
        """__str__ function from distutils.version.LooseVersion"""
        return self.vstring

    def __repr__(self):
        """__repr__ function adapted from distutils.version.LooseVersion"""
        return "MunkiLooseVersion ('%s')" % str(self)

    def __init__(self, vstring=None):
        """init method"""
        if vstring is None:
            # treat None like an empty string
            self.parse('')
        if vstring is not None:
            try:
                if isinstance(vstring, unicode):
                    # unicode string! Why? Oh well...
                    # convert to string so version.LooseVersion doesn't choke
                    vstring = vstring.encode('UTF-8')
            except NameError:
                # python 3
                pass
            self.parse(str(vstring))

    def _pad(self, version_list, max_length):
        """Pad a version list by adding extra 0 components to the end
        if needed"""
        # copy the version_list so we don't modify it
        cmp_list = list(version_list)
        while len(cmp_list) < max_length:
            cmp_list.append(0)
        return cmp_list

    def _compare(self, other):
        """Compare MunkiLooseVersions"""
        if not isinstance(other, MunkiLooseVersion):
            other = MunkiLooseVersion(other)

        max_length = max(len(self.version), len(other.version))
        self_cmp_version = self._pad(self.version, max_length)
        other_cmp_version = self._pad(other.version, max_length)
        cmp_result = 0
        for index, value in enumerate(self_cmp_version):
            try:
                cmp_result = _cmp(value, other_cmp_version[index])
            except TypeError:
                # integer is less than character/string
                if isinstance(value, int):
                    return -1
                return 1
            if cmp_result:
                return cmp_result
        return cmp_result

    def __hash__(self):
        """Hash method"""
        return hash(self.version)

    def __eq__(self, other):
        """Equals comparison"""
        return self._compare(other) == 0

    def __ne__(self, other):
        """Not-equals comparison"""
        return self._compare(other) != 0

    def __lt__(self, other):
        """Less than comparison"""
        return self._compare(other) < 0

    def __le__(self, other):
        """Less than or equals comparison"""
        return self._compare(other) <= 0

    def __gt__(self, other):
        """Greater than comparison"""
        return self._compare(other) > 0

    def __ge__(self, other):
        """Greater than or equals comparison"""
        return self._compare(other) >= 0


def pkg_ref_count(pkginfo_path, catalog_items):
    '''Returns the number of pkginfo items containing a reference to
    the installer_item_location in pkginfo_path and the relative path to
    the installer_item_location'''
    filepath = os.path.join(PKGSINFO_PATH, os.path.normpath(pkginfo_path))
    try:
        plistdata = readPlist(filepath)
    except (ExpatError, IOError):
        return 0, ''
    pkg_path = plistdata.get('installer_item_location')
    if not pkg_path:
        return 0, ''
    matching_count = 0
    if catalog_items:
        matches = [item for item in catalog_items
                   if item.get('installer_item_location') == pkg_path]
        matching_count = len(matches)
    return matching_count, pkg_path


def process_file(pkginfo_path):
    '''Worker function called by our multiprocessing pool. Reads a pkginfo
    file and returns a tuple of name, version, catalogs, and relative path'''
    filepath = os.path.join(PKGSINFO_PATH, os.path.normpath(pkginfo_path))
    try:
        pkginfo = readPlist(filepath)
    except (ExpatError, IOError):
        return ()
    return (pkginfo.get('name', 'NO_NAME'),
            pkginfo.get('version', 'NO_VERSION'),
            pkginfo.get('catalogs', []),
            pkginfo_path)


def any_files_in_list_newer_than(files, filepath):
    '''Returns true if any file in the list of files
    is newer that filepath'''
    try:
        mtime = os.stat(filepath).st_mtime
    except OSError:
        return True
    for fname in files:
        fullpath = os.path.join(PKGSINFO_PATH, fname)
        if os.stat(fullpath).st_mtime > mtime:
            return True
    return False


def record(message=None, percent_done=None):
    '''Record a status message for a long-running process'''
    record_status(
        PKGSINFO_STATUS_TAG, message=message, percent_done=percent_done)


class PkginfoFile(models.Model):
    '''Placeholder so we get permissions entries in the admin database'''
    pass


class Pkginfo(Plist):
    '''Models pkginfo items'''
    @classmethod
    def data(cls):
        '''Returns a structure with itemnames, versions, and filepaths'''
        def sortFunc(a):
            """Internal comparison function for use in sorting"""
            return MunkiLooseVersion(a[0])
        record(message='Starting scan of pkgsinfo data')
        files = cls.list('pkgsinfo')
        record(message='Processing %s files' % len(files))
        all_catalog = os.path.join(CATALOGS_PATH, 'all')
        try:
            all_items = readPlist(all_catalog)
        except (ExpatError, OSError, IOError):
            all_items = []
        use_slower_approach = False
        if len(all_items) != len(files):
            LOGGER.debug('number of files differ from all catalog')
            use_slower_approach = True
        elif any_files_in_list_newer_than(files, all_catalog):
            LOGGER.debug('files newer than all catalog')
            use_slower_approach = True
        pkginfo_dict = defaultdict(list)
        record(message='Assembling pkgsinfo data')
        if use_slower_approach:
            LOGGER.debug("using slower approach")
            # read the individual pkgsinfo files but use four threads
            # to speed things up a bit since we wait a lot for I/O
            pool = ThreadPool(processes=4)
            tuples = pool.map(process_file, files)
            for name, version, catalogs, pathname in tuples:
                pkginfo_dict[name].append((version, catalogs, pathname))
        else:
            LOGGER.debug("using faster approach")
            # use the data in the all catalog; one file read instead
            # of hundreds or thousands
            for index, item in enumerate(all_items):
                name = item.get('name', 'NO_NAME')
                version = item.get('version', 'NO_VERSION')
                catalogs = item.get('catalogs', [])
                pathname = files[index]
                pkginfo_dict[name].append((version, catalogs, pathname))
        for key in pkginfo_dict.keys():
            pkginfo_dict[key].sort(key=sortFunc, reverse=True)
        LOGGER.debug('Sorted pkgsinfo dict')

        # now convert to a list of lists
        pkginfo_list = []
        for key, value in pkginfo_dict.items():
            pkginfo_list.append([key, value])
        LOGGER.debug('Converted to tuple')
        record(message='Completed assembly of pkgsinfo data')
        return pkginfo_list

    @classmethod
    def mass_delete(cls, pathname_list, user, delete_pkgs=False):
        '''Deletes pkginfo files from a list and optionally deletes the
        associated installer items (pkgs)'''
        errors = []
        catalog_items = []
        if delete_pkgs:
            # cache the catalog_items once; we don't want to incur the
            # overhead of reading the 'all' catalog multiple times
            catalog_items = Catalog.detail('all')

        for pathname in pathname_list:
            delete_this_pkg = False
            if delete_pkgs:
                ref_count, pkg_path = pkg_ref_count(pathname, catalog_items)

pkgsinfo/templates/pkgsinfo/detail.html
<div>
    <img src="{{ icon_url }}" class='pkginfo-icon pull-left' height='32'/>
    <h4 id='pathname' data-installer-item-path='{{ installer_item_path }}'>{{ pathname }}</h4>
</div>
{% if perms.pkgsinfo.delete_pkginfofile %}
<div class='pull-right' id='delete_btn'>
    <button type="button" class="btn btn-danger" onClick="showDeleteConfirmationModal()">Delete</button>
</div>
{% endif %}
{% if perms.pkgsinfo.change_pkginfofile %}
<div class='pull-right hidden' id='save_and_cancel'>
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#cancelEditConfirmationModal">Cancel</button>
  <button type="button" class="btn btn-success" onClick="savePkginfoItem()">Save</button>
</div>
{% else %}
<div class='pull-right hidden' id='save_and_cancel'>
  <span class="bg-danger">You don't have permissions to make changes here.</span>
  <button type="button" class="btn" onClick="cancelEdit()">Cancel</button>
</div>
{% endif %}
<div role="tabpanel">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist" id="editortabs">
    <li role="presentation" class="active">
      <a href="#basicstab" aria-controls="basicstab" role="tab" data-toggle="tab">Basics</a>
    </li>
    <li role="presentation">
      <a href="#detailtab" aria-controls="editortab" role="tab" data-toggle="tab">Details</a>
    </li>
    <li role="presentation">
      <a href="#plisttab" aria-controls="plisttab" role="tab" data-toggle="tab">Plist</a>
    </li>
  </ul>
  <!-- Tab panes -->
  <div class="tab-content" id="item_editor">
    <div role="tabpanel" class="tab-pane active" id="basicstab">
        <div id="basics" class="plist-editor"></div>
    </div>
    <div role="tabpanel" class="tab-pane" id="detailtab">
        <div id="detail" class="plist-editor"></div>
    </div>
    <div role="tabpanel" class="tab-pane" id="plisttab">
        <div id='plist'>{{ plist_text }}</div>
    </div>
   </div>
</div>
<!--
Bootstrap modal for confirming pkginfo deletion
-->
<div class="modal fade" id="deleteConfirmationModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete pkginfo?</h4>
      </div>
      <div class="modal-body">
        <p>Really delete <strong>{{ pathname }}</strong>?</p>
        <p>This action cannot be undone.</p>
        <div id="deleteConfirmationModalInstallerItem" class='hidden'>
            <div class="checkbox pull-right">
                <label>
                    <input type="checkbox" id="delete_pkg">
                    Also delete installer item
                </label>
            </div>
            <br>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal" onClick="deletePkginfoItem()">Delete</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for confirming canceling editing
-->
<div class="modal fade" id="cancelEditConfirmationModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Discard your changes?</h4>
      </div>
      <div class="modal-body">
        <p>Really discard your changes to <strong>{{ pathname }}</strong>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"  onClick="cancelEdit()">Discard Changes</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Continue Editing</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for saving or canceling when loading a different pkginfo
-->
<div class="modal fade" id="saveOrCancelConfirmationModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Save your changes?</h4>
      </div>
      <div class="modal-body">
        <p>Save your changes to <strong>{{ pathname }}</strong> before proceeding?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal" onClick="discardChangesAndLoadNext()">Discard Changes</button>
        <button type="button" class="btn btn-success" data-dismiss="modal" onClick="saveChangesAndLoadNext()">Save Changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

pkgsinfo/templates/pkgsinfo/pkgsinfo.html
{% extends 'base.html' %}
{% load pkgsinfo_extras %}

{% block extra_style %}
{% load static %}
<link rel="stylesheet" href="{% get_static_prefix %}css/plisteditor.css" type="text/css" media="all" />
<link rel="stylesheet" href="{% get_static_prefix %}pkgsinfo/css/pkgsinfo.css" type="text/css" media="all" />
<link rel="stylesheet" href="{% get_static_prefix %}css/bootstrap-chosen.css" type="text/css" media="all" />
{% endblock extra_style %}

{% block java_script %}
{% load static %}
<script type='text/javascript'
    src='{% get_static_prefix %}js/jquery.plisteditor.js'>
</script>
<script type='text/javascript'
    src='{% get_static_prefix %}js/plistparser.js'>
</script>
<script type="text/javascript" charset="utf-8"
    src="{% get_static_prefix %}js/ace/src-min-noconflict/ace.js">
</script>
<script type='text/javascript'
    src='{% get_static_prefix %}js/mwa_editor_shared.js'>
</script>
<script type='text/javascript'
    src='{% get_static_prefix %}pkgsinfo/js/pkgsinfo.js'>
</script>
<script type='text/javascript'
    src='{% get_static_prefix %}js/chosen.jquery.min.js'>
</script>
{% endblock java_script %}

{% block content %}
<div class="row-fluid">
  <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
    <div id='item_list'>
        <div class="form-inline">
            <div class="form-group">
                <div class="left-inner-addon">
                    <span class="icon-addon">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </span>
                    <input type="search" class="form-control" id="listSearchField" placeholder="Filter" value="{{search}}">
                </div>
            </div>
            <div class="form-group">
                <div class="btn-group">
                      <button type="button" id="catalog_dropdown"
                              class="btn btn-default dropdown-toggle" data-value="{{catalog}}" data-toggle="dropdown"
                              aria-haspopup="true" aria-expanded="false">
                          {{catalog}} <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" id="catalog_dropdown_list">
                          <li><a href="#">all</a></li>
                      </ul>
                  </div>
            </div>
            <div class="form-group pull-right">
              <div class="btn-group">
                  <button type="button" id="massaction_dropdown"
                          class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu dropdown-menu-right" id="massaction_dropdown_list">
                      <li class="disabled"><a href="#" id="mass_delete">Delete items…</a></li>
                      <li class="disabled"><a href="#" id="mass_edit_catalogs">Edit catalogs…</a></li>
                  </ul>
              </div>
            </div>
        </div>
        <table class="table table-striped table-condensed wraptext" id='list_items' style="width:100%">
          <thead>
            <tr><th>Name</th><th>Version</th></tr>
          </thead>
          <tbody>
              <!-- table is filled via AJAX/JSON calls by DataTables -->
          </tbody>
        </table>
    </div>
  </div>
  <div class='col-xs-7 col-sm-7 col-md-7 col-lg-7'>
    <div id="pkginfo_item_detail"></div>
  </div>
</div>
<!-- data storage -->
<div id="data_storage"/>
<!--
Bootstrap modal for mass editing pkginfo items
-->
<div class="modal fade" id="massEditModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Edit catalogs for selected items</h4>
      </div>
      <div class="modal-body">
          <p id="massEditModalBodyText">Edit catalogs for the selected pkginfo items:</p>
          <div class="row">
               <div class="col-md-6">
                   <div class="form-group">
                        <label for="catalogs_to_add">Add:</label>
                        <select multiple class="form-control chosen-select" data-placeholder=" " id='catalogs_to_add'>
                          <option>testing</option>
                        </select>
                   </div>
              </div>
              <div class="col-md-6">
                  <div class="form-group">
                       <label for="catalogs_to_delete">Remove:</label>
                       <select multiple class="form-control chosen-select" data-placeholder=" " id='catalogs_to_delete'>
                         <option>testing</option>
                       </select>
                  </div>
              </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal" onClick="massEditCatalogs()">Change</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for confirming mass pkginfo deletion
-->
<div class="modal fade" id="massDeleteConfirmationModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete selected pkginfo items?</h4>
      </div>
      <div class="modal-body">
        <p id="massDeleteConfirmationModalBodyText">Really delete the selected pkginfo items?</p>
        <p>This action cannot be undone.</p>
        <div class="checkbox pull-right">
            <label>
                <input type="checkbox" id="mass_delete_pkg">
                Also delete installer items
            </label>
        </div>
        <br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal" onClick="deletePkginfoList()">Delete</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for showing process progress
-->
<div class="modal fade" data-backdrop="static" id="process_progress">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="process_progress_title_text">Processing...</h4>
      </div>
      <div class="modal-body">
          <div class="progress">
            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
              <span class="sr-only">Indeterminate progress</span>
              <div id='process_progress_status_text'>&nbsp;</div>
            </div>
          </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<!--
Bootstrap modal for errors
-->
<div class="modal fade" data-backdrop="static" id="errorModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title text-danger">
            <span class="glyphicon glyphicon-alert text-danger" aria-hidden="true"></span>
            <span id="errorModalTitleText">Error</span>
        </h4>
      </div>
      <div class="modal-body">
        <form>
          <p id="errorModalDetailText">An unexpected error occurred.</p>
        </form>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">OK</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
{% endblock content %}